CREATE TABLE SALES_REP
{
  REP_ID CHAR (2) PRIMARY KEY
  FIRST_NAME CHAR (20),
  LAST_NAME CHAR (20),
  ADDRESS CHAR (20),
  CITY CHAR (15),
  STATE CHAR (2),
  POSTAL CHAR (5),
  CELL_PHONE CHAR (12),
  COMMISSION DECIMAL (7,2),
  RATE DECIMAL (3,2)
};
