SELECT INVOICE_NUM, INVOICE_LINE.ITEM_ID, DESCRIPTION, QUANTITY, QUOTED_PRICE, PRICE
FROM INVOICE_LINE, ITEM
WHERE (INVOICE_LINE.ITEM_ID = ITEM.ITEM_ID);
--The ITEM_ID could also come from the ITEM table
