1. 
SELECT ITEM_ID, DESCRIPTION, PRICE
FROM ITEM;
2. 
SELECT *
FROM INVOICES;
3. 
SELECT FIRST_NAME, LAST_NAME, CREDIT_LIMIT
FROM CUSTOMER
WHERE CREDIT_LIMIT >= 1000;
4. 
SELECT INVOICE_NUM
FROM INVOICES
WHERE CUST_ID = '125' AND INVOICE_DATE = '2021-11-15';
5. 
SELECT CUST_ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE REP_ID = '10' OR REP_ID = '15';
6. 
SELECT ITEM_ID, DESCRIPTION
FROM ITEM
/*
WHERE CATEGORY != 'HOR';
WHERE CATEGORY <> 'HOR';
  */
WHERE NOTE CATEGORY = 'HOR';
7. 
SELECT ITEM_ID, DESCRIPTION, ON_HAND
FROM ITEM
--WHERE ON_HAND >= 10 AND ON_HAND <=30;
--WHERE ON_HAND BETWEEN 10 AND 30;
WHERE ON_HAND >9 AND ON_HAND <31;
8. 
SELECT ITEM_ID, DESCRIPTION, (ON_HAND*PRICE) AS ON_HAND_VALUE
FROM ITEM
WHERE CATEGORY = 'CAT';
9.
SELECT ITEM_IID, DESCRIPTION, (ON_HAND*PRICE) AS ON_HAND_VALUE
FROM ITEM
WHERE (ON_HAND*PRICE) >= 1500;
10.
SELECT ITEM_ID, DESCRIPTION
FROM ITEM
WHERE CATETGORY IN ('FSH','BRD');
11.
SELECT CUST_ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE FIRST_NAME LIKE 'S%';
12. 
SELECT *
FROM ITEM
ORDER BY DESCRIPTION;
13. 
SELECT *
FROM ITEM
ORDER BY LOCATION, ITEM_ID;
14. 
SELECT COUNT (*)
FROM CUSTOMER
WHERE BALANCE > CREDIT_LIMIT;
15. 
SELECT SUM(BALANCE)
FROM CUSTOMER
WHERE (REP_ID = '10' AND BALANCE < CREDIT_LIMIT);
16. 
SELECT ITEM_ID, DESCRIPTION, (ON_HAND * PRICE) AS ON_HAND_VALUE
FROM ITEM
WHERE ON_HAND > (SELECT AVG (ON_HAND)
                    FROM ITEM);
17. 
(SELECT MIN(PRICE)
FROM ITEM);
18. 
SELECT ITEM_ID, DESCRIPTION, PRICE
FROM ITEM
WHERE PRICE IN (SELECT MIN(PRICE)
                  FROM ITEM);
19. 
SELECT SUM(BALANCE)
FROM CUSTOMER
GROUP BY REP_ID
ORDER BY REP_ID;
20. 
SELECT SUM(BALANCE)
FROM CUSTOMER
GROUP BY REP_ID
HAVING SUM(BALANCE) > 150
ORDER BY REP_ID;
21.
SELECT ITEM_ID
FROM ITEM
WHERE DESCRIPTION IS NULL;


















